spring.application.name=${SPRING_APPLICATION_NAME}

spring.mongodb.uri=${MONGO_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration-in-ms=${JWT_EXPIRATION}

microservice.uri=${MICROSERVICE_URI}
frontend.url=${FRONTEND_URL}

server.port=${PORT:8080}

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*

management.health.mongodb.enabled=false